name: Workflow to build the go binary 
run-name: Building the Go binary
on: 
  push: 
    branches: [main]
jobs: 
  Build: 
    runs-on: ubuntu-latest ## the Linux env being used to compile the binary
    steps: 
    - name: Fetch the Code
      uses: actions/checkout@v3

    - name: Set up the Go environment 
      uses: actions/setup-go@v5.5.0
      with: 
        go-version-file: go.sum

    - name: Installing dependencies
      run: go mod download

    - name: Build the Final Binary
      run: go build hexDumper.go

    - name: Upload the packaged Binary
      uses: actions/upload-artifact@v4.6.2
      with: 
        path: hexDumper-go
